require "pry"
require "nokogiri"
require "open-uri"
require "watir"
require "headless"

require "./lib/shelter_pets/version"
require "./lib/shelter_pets/cli"
require "./lib/shelter_pets/dog"
require "./lib/shelter_pets/scraper"
